workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "com.example.smsautomationapp"
      java: 17
      node: 16
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'master'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Get Flutter/React Native dependencies (if any)
        script: | 
          # npm install  # Uncomment if you have Node dependencies
          echo "Skipping npm install - no Node dependencies detected"

      - name: Set up keystore for signing
        script: | 
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          # Alternatively use $CM_KEYSTORE_PATH for direct path

      - name: Build Android Debug APK
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Build Android Release APK
        script: | 
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Run unit tests
        script: | 
          ./gradlew test --no-daemon
        ignore_failure: true

      - name: Run instrumented tests (optional)
        script: | 
          # ./gradlew connectedAndroidTest --no-daemon
          echo "Skipping instrumented tests - requires emulator"
        ignore_failure: true

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
      - app/build/test-results/**/*.xml
      - app/build/reports/**/*

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

      slack:
        channel: '#builds'
        notify_on_build_start: false
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  android-release-workflow:
    name: Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.smsautomationapp"
      java: 17
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
      cancel_previous_builds: false
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android App Bundle
        script: | 
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon --stacktrace

      - name: Build Release APK
        script: | 
          ./gradlew assembleRelease --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
        submit_as_draft: false
        rollout_fraction: 0.1
        changes_not_sent_for_review: false
        in_app_update_priority: 3

  android-debug-workflow:
    name: Android Debug Build (Fast)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.smsautomationapp"
      java: 17
    triggering:
      events:
        - pull_request
      cancel_previous_builds: true
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Debug APK
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Run unit tests
        script: | 
          ./gradlew testDebugUnitTest --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/test-results/**/*.xml

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: false
          failure: true

